-keep class com.lampa.player.domain.model.** { *; }
-keep class com.lampa.player.data.tmdb.TmdbMetadata { *; }
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**
-keepattributes Signature
-keepattributes *Annotation*
